import { Project, Supplier, Requirement, ConstraintResult, ProjectDocument, Evidence } from '../types';

export const INITIAL_EVIDENCE: Evidence[] = [
  {
    id: 'ev-1',
    supplierId: 's1',
    supplierName: 'Vertex Manufacturing',
    docName: 'Vertex_Manufacturing_Commercial_Quote_v2.pdf',
    pageNumber: 3,
    sectionTitle: 'Section 2.4 - Delivery & Quality Guarantees',
    extractedText: 'Vertex guarantees a maximum lead time of 15 calendar days from PO confirmation. Full ISO9001:2015 certification verified under Registrant #489201.',
    confidenceScore: 0.98,
    evidenceType: 'Compliance',
  },
  {
    id: 'ev-2',
    supplierId: 's1',
    supplierName: 'Vertex Manufacturing',
    docName: 'Vertex_Manufacturing_Commercial_Quote_v2.pdf',
    pageNumber: 1,
    sectionTitle: 'Section 1.2 - Commercial Pricing',
    extractedText: 'Unit price for 5,000 units of A380 Aluminum Alloy Motor Housings is $9.00/unit (Total $45,000). Minimum order quantity is set at 1,000 units.',
    confidenceScore: 0.99,
    evidenceType: 'Commercial',
  },
  {
    id: 'ev-3',
    supplierId: 's2',
    supplierName: 'Apex Industrial',
    docName: 'Apex_Industrial_Terms_2026.pdf',
    pageNumber: 2,
    sectionTitle: 'Section 4.1 - Order Requirements',
    extractedText: 'Standard Minimum Order Quantity (MOQ) for cast aluminum components is 2,000 units per batch. Standard lead time is 25 business days.',
    confidenceScore: 0.95,
    evidenceType: 'Commercial',
  },
  {
    id: 'ev-4',
    supplierId: 's3',
    supplierName: 'Nova Components',
    docName: 'Nova_Components_Company_Profile.pdf',
    pageNumber: 5,
    sectionTitle: 'Section 6 - Quality & Audits',
    extractedText: 'Nova Components ISO9001 quality audit is currently in process for renewal (expiration date was Dec 2025). Re-certification anticipated Q4.',
    confidenceScore: 0.91,
    evidenceType: 'Quality',
  },
];

export const MOTOR_HOUSING_SUPPLIERS: Supplier[] = [
  {
    id: 's1',
    name: 'Vertex Manufacturing',
    location: 'Stuttgart, Germany',
    status: 'QUALIFIED',
    rawCost: 45000,
    rawMoq: 1000,
    rawTime: 15,
    isoCertified: true,
    scores: {
      cost: 82,
      quality: 96,
      leadTime: 98,
      risk: 94,
      sustainability: 88,
      overall: 91,
    },
    strengths: [
      'Fastest guaranteed lead time (15 days)',
      'Lowest risk profile with verified ISO9001:2015',
      'Fully compliant with MOQ <= 1,000 units requirement',
      'Automated CNC precision tolerance (+/- 0.02mm)',
    ],
    weaknesses: [
      'Unit price is 18% higher than lowest bidder (Apex)',
    ],
    primaryEvidence: INITIAL_EVIDENCE[0],
    riskDetails: 'Low supply chain vulnerability. Dual-source raw aluminum inventory in EU.',
    contactEmail: 'bids@vertex-mfg.de',
  },
  {
    id: 's2',
    name: 'Apex Industrial',
    location: 'Ohio, USA',
    status: 'CONDITIONALLY_QUALIFIED',
    rawCost: 38000,
    rawMoq: 2000,
    rawTime: 25,
    isoCertified: true,
    scores: {
      cost: 98,
      quality: 86,
      leadTime: 65,
      risk: 72,
      sustainability: 70,
      overall: 78,
    },
    strengths: [
      'Lowest overall commercial proposal ($38,000 total)',
      'High-capacity production line available immediately',
      'Robust domestic freight network',
    ],
    weaknesses: [
      'Minimum order quantity (2,000 units) exceeds maximum constraint',
      'Lead time of 25 days breaches preferred threshold (20 days)',
    ],
    primaryEvidence: INITIAL_EVIDENCE[2],
    riskDetails: 'Moderate risk due to high MOQ requiring excess warehouse holding cost.',
    contactEmail: 'sales@apex-industrial.com',
  },
  {
    id: 's3',
    name: 'Nova Components',
    location: 'Taichung, Taiwan',
    status: 'REJECTED',
    rawCost: 42000,
    rawMoq: 500,
    rawTime: 20,
    isoCertified: false,
    scores: {
      cost: 88,
      quality: 68,
      leadTime: 78,
      risk: 48,
      sustainability: 52,
      overall: 62,
    },
    strengths: [
      'Very flexible low MOQ (500 units)',
      'Competitive middle-tier pricing ($42,000)',
    ],
    weaknesses: [
      'ISO9001 certification expired & pending audit',
      'High risk of quality defect rate during ramping',
    ],
    primaryEvidence: INITIAL_EVIDENCE[3],
    riskDetails: 'High risk due to unverified quality certification compliance.',
    contactEmail: 'inquiries@novacomp.tw',
  },
];

export const MOTOR_HOUSING_REQUIREMENTS: Requirement[] = [
  {
    id: 'req-1',
    category: 'Material',
    name: 'Base Alloy Standard',
    expected: 'A380 Aluminum Die Cast',
    priority: 'MANDATORY',
    description: 'Must withstand operating thermal limits up to 180°C.',
  },
  {
    id: 'req-2',
    category: 'Commercial',
    name: 'Maximum MOQ',
    expected: '<= 1,000 units',
    priority: 'MANDATORY',
    description: 'Storage capacity limited at primary staging facility.',
  },
  {
    id: 'req-3',
    category: 'Logistics',
    name: 'Maximum Lead Time',
    expected: '<= 20 days',
    priority: 'MANDATORY',
    description: 'Required to meet Q3 assembly line production milestone.',
  },
  {
    id: 'req-4',
    category: 'Compliance',
    name: 'ISO9001 Certification',
    expected: 'Active ISO9001:2015',
    priority: 'MANDATORY',
    description: 'Required by OEM quality governance standard.',
  },
];

export const MOTOR_HOUSING_CONSTRAINTS: ConstraintResult[] = [
  {
    requirementId: 'req-1',
    requirementName: 'Base Alloy Standard',
    expected: 'A380 Aluminum',
    supplierResults: {
      s1: { status: 'PASS', actualValue: 'A380 Die Cast Alloy', notes: 'Verified in Spec Sheet p.2' },
      s2: { status: 'PASS', actualValue: 'A380 Die Cast Alloy', notes: 'Verified in Tech Spec p.1' },
      s3: { status: 'PASS', actualValue: 'A380 Equivalent', notes: 'Substituted alloy variant' },
    },
  },
  {
    requirementId: 'req-2',
    requirementName: 'Maximum MOQ',
    expected: '<= 1,000 units',
    supplierResults: {
      s1: { status: 'PASS', actualValue: '1,000 units', notes: 'Exact match' },
      s2: { status: 'FAIL', actualValue: '2,000 units', notes: 'Exceeds max allowed batch size' },
      s3: { status: 'PASS', actualValue: '500 units', notes: 'Below maximum limit' },
    },
  },
  {
    requirementId: 'req-3',
    requirementName: 'Maximum Lead Time',
    expected: '<= 20 days',
    supplierResults: {
      s1: { status: 'PASS', actualValue: '15 days', notes: 'Exceeds goal by 5 days' },
      s2: { status: 'WARNING', actualValue: '25 days', notes: '5 days over requirement' },
      s3: { status: 'PASS', actualValue: '20 days', notes: 'On the limit' },
    },
  },
  {
    requirementId: 'req-4',
    requirementName: 'ISO9001 Certification',
    expected: 'Active ISO9001',
    supplierResults: {
      s1: { status: 'PASS', actualValue: 'Active (Cert #489201)', notes: 'Valid through 2028' },
      s2: { status: 'PASS', actualValue: 'Active (Cert #9001-US)', notes: 'Valid through 2027' },
      s3: { status: 'FAIL', actualValue: 'Expired / Pending', notes: 'Expired Dec 2025' },
    },
  },
];

export const MOTOR_HOUSING_DOCS: ProjectDocument[] = [
  {
    id: 'doc-1',
    name: 'Motor_Housing_RFP_Specification.pdf',
    size: '2.4 MB',
    type: 'PDF',
    uploadedAt: '2026-08-09',
    status: 'Ready',
    pagesCount: 14,
  },
  {
    id: 'doc-2',
    name: 'Vertex_Manufacturing_Commercial_Quote_v2.pdf',
    size: '1.8 MB',
    type: 'PDF',
    uploadedAt: '2026-08-09',
    status: 'Ready',
    pagesCount: 8,
  },
  {
    id: 'doc-3',
    name: 'Apex_Industrial_Terms_2026.pdf',
    size: '3.1 MB',
    type: 'PDF',
    uploadedAt: '2026-08-09',
    status: 'Ready',
    pagesCount: 12,
  },
  {
    id: 'doc-4',
    name: 'Nova_Components_Company_Profile.pdf',
    size: '4.5 MB',
    type: 'PDF',
    uploadedAt: '2026-08-09',
    status: 'Ready',
    pagesCount: 19,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Motor Housing Procurement',
    description: 'Sourcing 5,000 precision A380 aluminum die-cast housings for EV drivetrain line B.',
    category: 'Automotive & Hardware',
    status: 'Analyzed',
    date: '2026-08-09',
    targetBudget: 50000,
    documents: MOTOR_HOUSING_DOCS,
    suppliers: MOTOR_HOUSING_SUPPLIERS,
    requirements: MOTOR_HOUSING_REQUIREMENTS,
    constraints: MOTOR_HOUSING_CONSTRAINTS,
  },
  {
    id: 'proj-2',
    name: 'Industrial Valve Sourcing',
    description: 'High-pressure forged stainless steel valves for primary chemical processing loop.',
    category: 'Heavy Industry',
    status: 'Analyzed',
    date: '2026-08-05',
    targetBudget: 120000,
    documents: [
      { id: 'doc-201', name: 'Valve_Tech_Specs.pdf', size: '1.2 MB', type: 'PDF', uploadedAt: '2026-08-05', status: 'Ready' },
      { id: 'doc-202', name: 'FlowTech_Proposal.pdf', size: '2.8 MB', type: 'PDF', uploadedAt: '2026-08-05', status: 'Ready' },
    ],
    suppliers: [
      {
        id: 's201',
        name: 'FlowTech Dynamics',
        location: 'Houston, TX',
        status: 'QUALIFIED',
        rawCost: 110000,
        rawMoq: 200,
        rawTime: 30,
        isoCertified: true,
        scores: { cost: 88, quality: 94, leadTime: 85, risk: 90, sustainability: 82, overall: 89 },
        strengths: ['API 6D certified', 'Proven pressure testing'],
        weaknesses: ['Higher freight costs'],
        primaryEvidence: INITIAL_EVIDENCE[0],
        riskDetails: 'Established supplier with strong regional logistics.',
      },
      {
        id: 's202',
        name: 'ValvCo Global',
        location: 'Milan, Italy',
        status: 'CONDITIONALLY_QUALIFIED',
        rawCost: 98000,
        rawMoq: 500,
        rawTime: 45,
        isoCertified: true,
        scores: { cost: 95, quality: 82, leadTime: 60, risk: 75, sustainability: 85, overall: 79 },
        strengths: ['Lowest initial quote'],
        weaknesses: ['International shipping delay risk'],
        primaryEvidence: INITIAL_EVIDENCE[1],
        riskDetails: 'Port congestion risk.',
      }
    ],
    requirements: [
      { id: 'r201', category: 'Pressure', name: 'Working Rating', expected: 'PN160 / 2500 PSI', priority: 'MANDATORY' },
    ],
    constraints: [],
  },
  {
    id: 'proj-3',
    name: 'Aluminum Bracket Sourcing',
    description: 'Structural mounting brackets for solar panel tilt frame array.',
    category: 'Renewable Energy',
    status: 'Draft',
    date: '2026-08-08',
    targetBudget: 35000,
    documents: [],
    suppliers: [],
    requirements: [],
    constraints: [],
  },
];
